version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: vk
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d vk" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"
    networks:
      - backend

  market:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: market
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:123@db:5432/vk?sslmode=disable
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./static/upload:/app/static/upload

networks:
  backend:
    driver: bridge